server:
  port: 80
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': #只要有人处理请求了，这个跨域就能生效
            allowedOrigins: #允许所有地址来源跨域
              - "*"
            allowedMethods: #允许所有请求方式跨域
              - "*"
            allowedHeaders: #复杂跨域的原因就是因为带来一些复杂的请求头导致
              - "*"
            allowCredentials: true #允许带一些安全标致跨域 比如：Cookie
      routes:
        - id: service-product
          uri: lb://service-product
          predicates:
            - Path=/admin/product/**

        - id: service-activity
          uri: lb://service-activity
          predicates:
            - Path=/admin/activity/**

        - id: service-item
          uri: lb://service-item
          predicates:
            - Path=/lock/**

        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/api/user/**

        - id: web-all
          uri: lb://web-all
          predicates:
            - Host=**.gmall.com
gmall:
  auth:
    authUrl:
      - /order/**
    noneAuthUrl:
      - /css/**
      - /js/**
      - /img/**
      - /login.html
      - /api/user/passport/login
    forbiddenUrl:
      - /api/inner/**
    loginPageUrl: http://passport.gmall.com/login.html