server:
  port: 80
spring:
  zipkin:
    base-url: http://192.168.6.200:9411
    sender:
      type: web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': #只要有人处理请求了，这个跨域就能生效
            allowedOrigins: #允许所有地址来源跨域
              - "*"
            allowedMethods: #允许所有请求方式跨域
              - "*"
      routes:
        - id: service-product
          uri: lb://service-product
          predicates:
            - Path=/admin/product/**