server:
  port: 8000
  tomcat:
    max-connections: 200
spring:
  zipkin:
    base-url: http://192.168.6.200:9411
    sender:
      type: web
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
feign:
  client:
    config:
      default:
        connectTimeout: 500
        readTimeout: 5000
        retryer: com.atguigu.gmall.common.retry.NeverRetry