server:
  port: 7000
spring:
  zipkin:
    base-url: http://192.168.6.200:9411
    sender:
      type: web
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration