server:
  port: 9002
#  tomcat:
#    max-connections: 200
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  zipkin:
    base-url: http://192.168.6.200:9411
    sender:
      type: web
  redis:
    password: Lfy123456
    host: 192.168.6.200
management:
  endpoints:
    web:
      exposure:
        include: "*"
gmall:
  thread-pool:
    corePoolSize: 4
    maximumPoolSize: 8
    queueCapacity: 2000
    keepAliveTime: 300
  bloom-filter:
    expected-insertions: 10000
    fpp: 0.0001
