server:
  port: 10030
  tomcat:
    max-connections: 200
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
management:
  endpoints:
    web:
      exposure:
        include: "*"
gmall:
  thread-pool:
    corePoolSize: 4
    maximumPoolSize: 8
    queueCapacity: 2000
    keepAliveTime: 300
  bloom-filter:
    expected-insertions: 10000
    fpp: 0.0001
