server:
  port: 9000
  tomcat:
    max-connections: 200
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.6.200:3306/gmall_product?ServerTimezone=UTC&CharacterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  zipkin:
    base-url: http://192.168.6.200:9411
    sender:
      type: web
  redis:
    host: 192.168.6.200
    password: Lfy123456
gmall:
  minio:
    endpoint: http://192.168.6.200:9000
    accessKey: admin
    secretKey: adminadmin
    bucketName: gmall
    max-img-size: 5242880
    max-video-size: 104857600
  bloom-filter:
    fpp: 0.0001
    expected-insertions: 500000