server:
  port: 9000
  tomcat:
    max-connections: 200
spring:
  profiles:
    include: shardingsphere
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.6.200:3306/gmall_product?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
gmall:
  minio:
    endpoint: http://192.168.6.200:9000
    accessKey: admin
    secretKey: adminadmin
    bucketName: gmall
    max-img-size: 5242880
    max-video-size: 104857600
  bloom-filter:
    fpp: 0.0001
    expected-insertions: 5000000
  thread-pool:
    core-pool-size: 4
    maximum-pool-size: 8
    queue-capacity: 2000
    keep-alive-time: 300
