server:
  port: 9000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.6.200:3306/gmall_product?ServerTimezone=UTC&CharacterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  zipkin:
    base-url: http://192.168.6.200:9411
    sender:
      type: web
